### ISSUE TITLE
Addition of stop alarm feature in the alarm clock 

### ISSUE THREAD

**Issue by Rishita489** [yashchaudhari008/Basic_Clock_App#3]
I suggest addition of stop alarm button in the alarm clock . It helps the user to stop the alarm clock while it is ringing .

**Comment by Rishita489** [comment]
Hey @yashchaudhari008 , can you please assign this issue the hacktoberfest label and assign it to me .

**Comment by Rishita489** [comment]
Hey @yashchaudhari008 , can you please assign this issue the hacktoberfest label and assign it to me .

**Comment by Rishita489** [comment]
I have send the PR . Can you please review and merge it .

**Comment by yashchaudhari008** [comment]
This repo is not participating in hacktoberfest. Check other repos on my profile that are participating. Thanks 👍
